# Challenge 3

In this challenge we will work on the `Orders.csv` data set in the previous [Subsetting and Descriptive Stats lab](../../lab-subsetting-and-descriptive-stats/your-code/main.ipynb). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

# Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [2]:
# import required libraries
import numpy as np
import pandas as pd

Next, import `Orders.csv` from the "subsetting" lab folder into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [3]:
# enter your code here
orders = pd.read_csv("../../lab-subsetting-and-descriptive-stats/your-code/Orders.csv")
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [4]:
# your code here
#Sub Problem 1

cust_spending = orders.groupby("CustomerID").agg({"amount_spent":"sum"})
c2 = cust_spending.copy()
#Sub problem 2
print(cust_spending.quantile(.95))

#Sub problem 3
cust_spending["Preferred"] = (cust_spending > cust_spending.quantile(.75)) & (cust_spending < cust_spending.quantile(.95))
cust_spending["VIP"] = c2 > c2.quantile(.95)
cust_spending = cust_spending.drop(columns = ["amount_spent"])
orders = pd.merge(orders, cust_spending, on='CustomerID')
orders

amount_spent    5840.182
Name: 0.95, dtype: float64

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,Preferred,VIP
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,True,False
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,True,False
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,True,False
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,True,False
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,True,False
5,5,536365,22752,2010,12,3,8,set 7 babushka nesting boxes,2,2010-12-01 08:26:00,7.65,17850,United Kingdom,15.30,True,False
6,6,536365,21730,2010,12,3,8,glass star frosted t-light holder,6,2010-12-01 08:26:00,4.25,17850,United Kingdom,25.50,True,False
7,7,536366,22633,2010,12,3,8,hand warmer union jack,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10,True,False
8,8,536366,22632,2010,12,3,8,hand warmer red polka dot,6,2010-12-01 08:28:00,1.85,17850,United Kingdom,11.10,True,False
9,47,536372,22632,2010,12,3,9,hand warmer red polka dot,6,2010-12-01 09:01:00,1.85,17850,United Kingdom,11.10,True,False
10,48,536372,22633,2010,12,3,9,hand warmer union jack,6,2010-12-01 09:01:00,1.85,17850,United Kingdom,11.10,True,False
11,49,536373,85123A,2010,12,3,9,white hanging heart t-light holder,6,2010-12-01 09:02:00,2.55,17850,United Kingdom,15.30,True,False
12,50,536373,71053,2010,12,3,9,white metal lantern,6,2010-12-01 09:02:00,3.39,17850,United Kingdom,20.34,True,False
13,51,536373,84406B,2010,12,3,9,cream cupid hearts coat hanger,8,2010-12-01 09:02:00,2.75,17850,United Kingdom,22.00,True,False
14,52,536373,20679,2010,12,3,9,edwardian parasol red,6,2010-12-01 09:02:00,4.95,17850,United Kingdom,29.70,True,False
15,53,536373,37370,2010,12,3,9,retro coffee mugs assorted,6,2010-12-01 09:02:00,1.06,17850,United Kingdom,6.36,True,False
16,54,536373,21871,2010,12,3,9,save the planet mug,6,2010-12-01 09:02:00,1.06,17850,United Kingdom,6.36,True,False
17,55,536373,21071,2010,12,3,9,vintage billboard drink me mug,6,2010-12-01 09:02:00,1.06,17850,United Kingdom,6.36,True,False
18,56,536373,21068,2010,12,3,9,vintage billboard love/hate mug,6,2010-12-01 09:02:00,1.06,17850,United Kingdom,6.36,True,False
19,57,536373,82483,2010,12,3,9,wood 2 drawer cabinet white finish,2,2010-12-01 09:02:00,4.95,17850,United Kingdom,9.90,True,False
20,58,536373,82486,2010,12,3,9,wood s/3 cabinet ant white finish,4,2010-12-01 09:02:00,6.95,17850,United Kingdom,27.80,True,False
21,59,536373,82482,2010,12,3,9,wooden picture frame white finish,6,2010-12-01 09:02:00,2.10,17850,United Kingdom,12.60,True,False
22,60,536373,82494L,2010,12,3,9,wooden frame antique white,6,2010-12-01 09:02:00,2.55,17850,United Kingdom,15.30,True,False
23,61,536373,84029G,2010,12,3,9,knitted union flag hot water bottle,6,2010-12-01 09:02:00,3.39,17850,United Kingdom,20.34,True,False
24,62,536373,84029E,2010,12,3,9,red woolly hottie white heart.,6,2010-12-01 09:02:00,3.39,17850,United Kingdom,20.34,True,False
25,63,536373,22752,2010,12,3,9,set 7 babushka nesting boxes,2,2010-12-01 09:02:00,7.65,17850,United Kingdom,15.30,True,False
26,64,536373,21730,2010,12,3,9,glass star frosted t-light holder,6,2010-12-01 09:02:00,4.25,17850,United Kingdom,25.50,True,False
27,66,536375,85123A,2010,12,3,9,white hanging heart t-light holder,6,2010-12-01 09:32:00,2.55,17850,United Kingdom,15.30,True,False
28,67,536375,71053,2010,12,3,9,white metal lantern,6,2010-12-01 09:32:00,3.39,17850,United Kingdom,20.34,True,False
29,68,536375,84406B,2010,12,3,9,cream cupid hearts coat hanger,8,2010-12-01 09:32:00,2.75,17850,United Kingdom,22.00,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397894,541776,581578,84997D,2011,12,5,12,childrens cutlery polkadot pink,8,2011-12-09 12:16:00,4.15,12713,Germany,33.20,False,False
397895,541777,581578,84997B,2011,12,5,12,childrens cutlery retrospot red,8,2011-12-09 12:16:00,4.15,12713,Germany,33.20,False,False
397896,541778,581578,84997C,2011,12,5,12,childrens cutlery polkadot blue,8,2011-12-09 12:16:00,4.15,12713,Germany,33.20,False,False
397897,541779,581578,22555,2011,12,5,12,plasters in tin strongman,12,2011-12-09 12:16:00,1.65,12713,Germany,19.80,False,False
397898,541780,581578,21914,2011,12,5,12,blue harmonica in box,12,2011-12-09 12:16:00,1.25,12713,Germany,15.00,False,False
397899,541781,581578,22549,2011,12,5,12,picture dominoes,24,2011-12-09 12:16:00,1.45,12713,Germany,34.80,False,False
397900,541782,581578,21918,2011,12,5,12,set 12 kids colour chalk sticks,24,2011-12-09 12:16:00,0.42,12713,Germany,10.08,False,False
397901,541783,581578,22992,2011,12,5,12,revolver wooden ruler,12,2011-12-09 12:16:00,1.95,12713,Germany,23.40,False,False
397902,541784,581578,22991,2011,12,5,12,giraffe wooden ruler,12,2011-12-09 12:16:00,1.95,12713,Germany,23.40,False,False
397903,541785,581578,23229,2011,12,5,12,vintage donkey tail game,6,2011-12-09 12:16:00,3.75,12713,Germany,22.50,False,False
397904,541786,581578,22622,2011,12,5,12,box of vintage alphabet blocks,6,2011-12-09 12:16:00,11.95,12713,Germany,71.70,False,False
397905,541787,581578,21506,2011,12,5,12,"fancy font birthday card,",12,2011-12-09 12:16:00,0.42,12713,Germany,5.04,False,False
397906,541788,581578,21507,2011,12,5,12,elephant birthday card,12,2011-12-09 12:16:00,0.42,12713,Germany,5.04,False,False
397907,541789,581578,23037,2011,12,5,12,candle holder silver madeline,12,2011-12-09 12:16:00,1.65,12713,Germany,19.80,False,False
397908,541790,581578,23550,2011,12,5,12,wrap alphabet poster,25,2011-12-09 12:16:00,0.42,12713,Germany,10.50,False,False
397909,541791,581578,22711,2011,12,5,12,wrap circus parade,25,2011-12-09 12:16:00,0.42,12713,Germany,10.50,False,False
397910,541792,581578,21497,2011,12,5,12,fancy fonts birthday wrap,25,2011-12-09 12:16:00,0.42,12713,Germany,10.50,False,False
397911,541793,581578,22704,2011,12,5,12,wrap red apples,25,2011-12-09 12:16:00,0.42,12713,Germany,10.50,False,False
397912,541794,581578,22585,2011,12,5,12,pack of 6 birdy gift tags,12,2011-12-09 12:16:00,1.25,12713,Germany,15.00,False,False
397913,541795,581578,23205,2011,12,5,12,charlotte bag vintage alphabet,10,2011-12-09 12:16:00,0.85,12713,Germany,8.50,False,False
397914,541796,581578,23201,2011,12,5,12,jumbo bag alphabet,10,2011-12-09 12:16:00,2.08,12713,Germany,20.80,False,False
397915,541797,581578,23515,2011,12,5,12,embroidered ribbon reel daisy,6,2011-12-09 12:16:00,2.08,12713,Germany,12.48,False,False
397916,541798,581578,22081,2011,12,5,12,ribbon reel flora + fauna,10,2011-12-09 12:16:00,1.65,12713,Germany,16.50,False,False
397917,541799,581578,22080,2011,12,5,12,ribbon reel polkadots,10,2011-12-09 12:16:00,1.65,12713,Germany,16.50,False,False
397918,541800,581578,23298,2011,12,5,12,spotty bunting,9,2011-12-09 12:16:00,4.95,12713,Germany,44.55,False,False
397919,541801,581578,22993,2011,12,5,12,set of 4 pantry jelly moulds,12,2011-12-09 12:16:00,1.25,12713,Germany,15.00,False,False
397920,541802,581578,22907,2011,12,5,12,pack of 20 napkins pantry design,12,2011-12-09 12:16:00,0.85,12713,Germany,10.20,False,False
397921,541803,581578,22908,2011,12,5,12,pack of 20 napkins red apples,12,2011-12-09 12:16:00,0.85,12713,Germany,10.20,False,False
397922,541804,581578,23215,2011,12,5,12,jingle bell heart antique silver,12,2011-12-09 12:16:00,2.08,12713,Germany,24.96,False,False
397923,541805,581578,22736,2011,12,5,12,ribbon reel making snowmen,10,2011-12-09 12:16:00,1.65,12713,Germany,16.50,False,False

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

# Q2: How to identify which country has the most VIP Customers?

# Q3: How to identify which country has the most VIP+Preferred Customers combined?

Provide your solution for Q2 below:

In [11]:
#Q2 groupby country agg vip customers
country_VIPs = orders.groupby("Country",as_index = False).agg({"VIP":"sum"})
#country_VIPs[country_VIPs["VIP"] == country_VIPs["VIP"].max()]
country_VIPs["VIP"].value_counts()

0.0        19
84185.0     1
205.0       1
54.0        1
364.0       1
248.0       1
36.0        1
294.0       1
3290.0      1
2080.0      1
3127.0      1
420.0       1
681.0       1
222.0       1
511.0       1
198.0       1
594.0       1
7077.0      1
898.0       1
Name: VIP, dtype: int64

In [ ]:
# Q3
vip_pref = orders.groupby("Country",as_index = False).agg({"VIP":"sum", "Preferred": "sum"})
vip_pref["VIP+Preferred"] = vip_pref["VIP"] + vip_pref["Preferred"]

vip_pref[vip_pref["VIP+Preferred"] == vip_pref["VIP+Preferred"].max()]